begin
set nocount on;

declare @p_survey_name					varchar(100)		= 'Demographics';
declare @p_requested_hashing_policy		char(10)			=  null;--'SA';

declare @hash_policy_map table 
(
	pseudonym varchar(150),
	policy_codifier char(10)
);
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Address1','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Address2','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CaseNumber','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Cell_Phone','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CHILD_MEDICAID_NUMBER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CL_EN_GEN_ID','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLID','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_0_ID_AGENCY','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_0_ID_NSO','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ALT_0_COMMENTS_ALT','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ALTERNATIVE_ENCOUNTER_1_TYPE_OTHER_ALT','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ATTENDEES_0_OTHER_VISIT_DESC','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CAC_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CARE_0_ER_OTHER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CARE_0_URGENT_OTHER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CI_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_EPA_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER_TXT','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_HEALTH_GENERAL_0_OTHER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Client_Id','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_INCOME_INKIND_OTHER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_INCOME_OTHER_SOURCES','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_LS_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_MEDICAID_NUMBER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NCCO_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NI_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NT_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NVC_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PC_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_FIRST ','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_FIRST','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_LAST','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PO_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PRA_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_RD_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_RP_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SCA_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SE_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TALKED_1_WITH_OTHER_ALT','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TELEHEALTH_REASON_OTHER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TELEHEALTH_TYPE_OTHER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VE_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VEC_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VQ_COMMENTS','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ClientID','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ClientName','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLReferralID','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Comments','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CRM_Client_ID','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Email','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ETO_CaseNo','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('First_Name','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Home_Phone','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO2','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO3','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER2','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER3','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON1','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON2','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON3','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME2','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME3','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_LAST NAME','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_NAME_FIRST','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_NAME_LAST','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_SSN','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON1_OTHER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON2_OTHER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON3_OTHER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON1_OTHER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON2_OTHER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON3_OTHER','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Last_Name','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Middle_Name','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('MN_INFANT_0_ID_2','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Notes','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Pager','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Passcode','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Question13','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Question14','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_0_NOTES','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_0_NAME_LAST','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_CELL','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_EMAIL','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_NAME_FIRST','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_PHONE_HOME','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_STREET','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_STREET2','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_WORK','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_PRIMARY_0_NAME','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_PRIMARY_1_LOCATION','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_SECONDARY_0_NAME','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_SECONDARY_1_LOCATION','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER1_DESC','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER2_DESC','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER3_DESC','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SSN','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Work_Phone','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLID, ','DUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Address1','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Address2','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CaseNumber','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Cell_Phone','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CHILD_MEDICAID_NUMBER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CL_EN_GEN_ID','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLID','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_0_ID_AGENCY','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_0_ID_NSO','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ALT_0_COMMENTS_ALT','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ALTERNATIVE_ENCOUNTER_1_TYPE_OTHER_ALT','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ATTENDEES_0_OTHER_VISIT_DESC','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CAC_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CARE_0_ER_OTHER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CARE_0_URGENT_OTHER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CI_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_EPA_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER_TXT','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_HEALTH_GENERAL_0_OTHER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Client_Id','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_INCOME_INKIND_OTHER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_INCOME_OTHER_SOURCES','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_LS_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_MEDICAID_NUMBER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NCCO_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NI_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NT_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NVC_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_O_ID_NSO','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PC_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_FIRST ','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_FIRST','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_LAST','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_O_NAME_FIRST','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_O_NAME_LAST','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PO_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PRA_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_RD_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_RP_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SCA_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SE_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TALKED_1_WITH_OTHER_ALT','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TELEHEALTH_REASON_OTHER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TELEHEALTH_TYPE_OTHER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VE_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VEC_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VQ_COMMENTS','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ClientID','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ClientName','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Comments','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CRM_Client_ID','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Email','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ETO_CaseNo','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('First_Name','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Home_Phone','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO2','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO3','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER2','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER3','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON1','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON2','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON3','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME2','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME3','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_LAST NAME','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_NAME_FIRST','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_NAME_LAST','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_SSN','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON1_OTHER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON2_OTHER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON3_OTHER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON1_OTHER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON2_OTHER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON3_OTHER','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Last_Name','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Middle_Name','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('MIECHV_READ_IID_12MO_PP_1','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('MIECHV_READ_IID_12MO_PP_2','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('MIECHV_READ_IID_12MO_PP_3','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('MIECHV_READ_IID_2MO_PP_1','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('MIECHV_READ_IID_2MO_PP_2','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('MIECHV_READ_IID_2MO_PP_3','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('MN_INFANT_0_ID_2','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Pager','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Passcode','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Question13','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Question14','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_0_NOTES','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_0_NAME_LAST','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_CELL','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_EMAIL','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_NAME_FIRST','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_PHONE_HOME','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_STREET','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_STREET2','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_WORK','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_PRIMARY_0_NAME','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_PRIMARY_1_LOCATION','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_SECONDARY_0_NAME','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_SECONDARY_1_LOCATION','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER1_DESC','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER2_DESC','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER3_DESC','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SSN','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Work_Phone','MCVDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Address1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Address2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Audit_Date','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('AuditDate','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CaseNumber','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Cell_Phone','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CHILD_MEDICAID_NUMBER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('City','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CL_EN_GEN_ID','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLID','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_0_ID_AGENCY','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_0_ID_NSO','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ALT_0_COMMENTS_ALT','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ALTERNATIVE_ENCOUNTER_1_TYPE_OTHER_ALT','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ATTENDEES_0_OTHER_VISIT_DESC','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CAC_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CARE_0_ER_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CARE_0_URGENT_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CI_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_DATE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_INCARCERATION_DATE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_INFANTDEATH_DATE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_LOST_CUSTODY_DATE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_MATERNAL_DEATH_DATE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_MISCARRIED_DATE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_MISCARRIED_DATE2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_EPA_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER_TXT','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_MIECHVP_COM','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_MIECHVP_FORM','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_MIECHVP_TRIBAL','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_OTHER1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_OTHER2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_OTHER3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_PFS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_MIECHVP_COM','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_MIECHVP_FORM','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_MIECHVP_TRIBAL','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_OTHER1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_OTHER2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_OTHER3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_HEALTH_GENERAL_0_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_HEALTH_PREGNANCY_0_EDD','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Client_Id','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_INCOME_INKIND_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_INCOME_OTHER_SOURCES','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_LS_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_MEDICAID_NUMBER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NCCO_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NI_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NT_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NVC_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_O_ID_NSO','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PC_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_DOB_INTAKE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_FIRST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_LAST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_O_DOB_INTAKE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_O_NAME_FIRST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_O_NAME_LAST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PO_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PRA_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_RD_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_RP_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SCA_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SE_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SECOND_0_CHILD_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TALKED_0_WITH_ALT','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TALKED_1_WITH_OTHER_ALT','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TELEHEALTH_REASON_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TELEHEALTH_TYPE_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_1_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_10_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_2_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_3_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_4_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_5_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_6_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_7_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_8_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_9_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VE_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VEC_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VQ_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ClientID','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ClientName','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Comments','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CRM_Client_ID','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Date_Created','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('DateOfReport','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('DW_AuditDate','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Email','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('EndDate','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ETO_CaseNo','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('First_Name','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Home_Phone','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_0_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_0_DOB2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_0_DOB3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INGEST_DATE1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INGEST_DATE2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INGEST_DATE3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INJ_DATE1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INJ_DATE2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INJ_DATE3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHERDT1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHERDT2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHERDT3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INGEST_DATE1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INGEST_DATE2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INGEST_DATE3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INJ_DATE1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INJ_DATE2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INJ_DATE3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_LAST NAME','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_NAME_FIRST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_NAME_LAST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_SSN','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON1_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON2_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON3_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REFDATE1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REFDATE2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REFDATE3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON1_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON2_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON3_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REFDATE1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REFDATE2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REFDATE3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Last_Name','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('LastModified','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Middle_Name','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('MN_INFANT_0_ID_2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Pager','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Passcode','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ProgramStartDate','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Question13','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Question14','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_0_NOTES','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_0_NAME_LAST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_CELL','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_EDD','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_EMAIL','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_NAME_FIRST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_PHONE_HOME','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_STREET','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_STREET2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_WORK','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_ZIP','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_PRIMARY_0_NAME','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_PRIMARY_1_LOCATION','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_SECONDARY_0_NAME','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_SECONDARY_1_LOCATION','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER1_DESC','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER2_DESC','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER3_DESC','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SSN','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('State','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('StatusDate','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SurveyDate','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SurveyDueDate','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Work_Phone','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ZipCode','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Address1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Address2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Audit_Date','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('AuditDate','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CaseNumber','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Cell_Phone','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CHILD_MEDICAID_NUMBER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('City','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CL_EN_GEN_ID','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLID','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_0_ID_AGENCY','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_0_ID_NSO','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ALT_0_COMMENTS_ALT','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ALTERNATIVE_ENCOUNTER_1_TYPE_OTHER_ALT','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ATTENDEES_0_OTHER_VISIT_DESC','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CAC_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CARE_0_ER_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CARE_0_URGENT_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CI_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_DATE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_INCARCERATION_DATE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_INFANTDEATH_DATE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_LOST_CUSTODY_DATE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_MATERNAL_DEATH_DATE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_MISCARRIED_DATE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_MISCARRIED_DATE2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_EPA_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER_TXT','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_MIECHVP_COM','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_MIECHVP_FORM','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_MIECHVP_TRIBAL','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_OTHER1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_OTHER2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_OTHER3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_PFS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_MIECHVP_COM','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_MIECHVP_FORM','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_MIECHVP_TRIBAL','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_OTHER1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_OTHER2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_OTHER3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_HEALTH_GENERAL_0_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_HEALTH_PREGNANCY_0_EDD','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Client_Id','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_INCOME_INKIND_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_INCOME_OTHER_SOURCES','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_LS_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_MEDICAID_NUMBER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NCCO_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NI_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NT_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NVC_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_O_ID_NSO','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PC_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_DOB_INTAKE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_FIRST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_LAST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_O_DOB_INTAKE','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_O_NAME_FIRST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_O_NAME_LAST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PO_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PRA_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_RD_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_RP_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SCA_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SE_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SECOND_0_CHILD_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TALKED_0_WITH_ALT','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TALKED_1_WITH_OTHER_ALT','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TELEHEALTH_REASON_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TELEHEALTH_TYPE_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_1_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_10_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_2_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_3_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_4_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_5_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_6_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_7_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_8_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_9_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VE_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VEC_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VQ_COMMENTS','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ClientID','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ClientName','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Comments','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CRM_Client_ID','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Date_Created','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('DateOfReport','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('DW_AuditDate','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Email','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('EndDate','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ETO_CaseNo','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('First_Name','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Home_Phone','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_0_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_0_DOB2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_0_DOB3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INGEST_DATE1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INGEST_DATE2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INGEST_DATE3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INJ_DATE1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INJ_DATE2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INJ_DATE3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHERDT1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHERDT2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHERDT3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INGEST_DATE1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INGEST_DATE2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INGEST_DATE3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INJ_DATE1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INJ_DATE2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INJ_DATE3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_LAST NAME','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_NAME_FIRST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_NAME_LAST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_SSN','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON1_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON2_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON3_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REFDATE1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REFDATE2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REFDATE3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON1_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON2_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON3_OTHER','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REFDATE1','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REFDATE2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REFDATE3','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Last_Name','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('LastModified','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Middle_Name','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('MN_INFANT_0_ID_2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Pager','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Passcode','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ProgramStartDate','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Question13','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Question14','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_0_NOTES','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_0_NAME_LAST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_CELL','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_DOB','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_EDD','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_EMAIL','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_NAME_FIRST','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_PHONE_HOME','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_STREET','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_STREET2','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_WORK','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_ZIP','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_PRIMARY_0_NAME','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_PRIMARY_1_LOCATION','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_SECONDARY_0_NAME','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_SECONDARY_1_LOCATION','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER1_DESC','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER2_DESC','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER3_DESC','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SSN','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('State','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('StatusDate','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SurveyDate','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SurveyDueDate','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Work_Phone','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ZipCode','MCVSA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Address1','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Address2','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CaseNumber','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Cell_Phone','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CHILD_MEDICAID_NUMBER','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CL_EN_GEN_ID','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLID','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_0_ID_AGENCY','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_0_ID_NSO','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ALT_0_COMMENTS_ALT','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ALTERNATIVE_ENCOUNTER_1_TYPE_OTHER_ALT','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ATTENDEES_0_OTHER_VISIT_DESC','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CAC_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CARE_0_ URGENT_OTHER','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CARE_0_ER_OTHER','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CI_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_EPA_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER_TXT','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_HEALTH_GENERAL_0_OTHER','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Client_Id','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_INCOME_INKIND_OTHER','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_INCOME_OTHER_SOURCES','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_LS_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_MEDICAID_NUMBER','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NCCO_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NI_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NT_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NVC_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PC_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_FIRST ','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_FIRST','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_LAST','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PO_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PRA_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_RD_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_RP_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SCA_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SE_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TALKED_1_WITH_OTHER_ALT','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VE_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VEC_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VQ_COMMENTS','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ClientID','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ClientName','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Comments','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CRM_Client_ID','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Email','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ETO_CaseNo','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('First_Name','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Home_Phone','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO2','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO3','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER2','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER3','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON1','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON2','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON3','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME2','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME3','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_LAST NAME','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_NAME_FIRST','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_NAME_LAST','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_SSN','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON1_OTHER','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON2_OTHER','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON3_OTHER','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON1_OTHER','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON2_OTHER','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON3_OTHER','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Last_Name','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Middle_Name','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Pager','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Passcode','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Question13','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Question14','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_0_NOTES','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_0_NAME_LAST','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_CELL','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_EMAIL','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_NAME_FIRST','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_PHONE_HOME','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_STREET','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_STREET2','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_WORK','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_PRIMARY_0_NAME','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_PRIMARY_1_LOCATION','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_SECONDARY_0_NAME','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_SECONDARY_1_LOCATION','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER1_DESC','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER2_DESC','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER3_DESC','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SSN','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Work_Phone','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLID','PFSDUA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Address1','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Address2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Audit_Date','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('AuditDate','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CaseNumber','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Cell_Phone','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CHILD_MEDICAID_NUMBER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('City','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CL_EN_GEN_ID','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLID','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_0_ID_AGENCY','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_0_ID_NSO','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ALT_0_COMMENTS_ALT','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ALTERNATIVE_ENCOUNTER_1_TYPE_OTHER_ALT','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_ATTENDEES_0_OTHER_VISIT_DESC','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CAC_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CARE_0_ER_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CARE_0_URGENT_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_CI_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_DATE','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_INCARCERATION_DATE','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_INFANTDEATH_DATE','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_LOST_CUSTODY_DATE','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_MATERNAL_DEATH_DATE','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_MISCARRIED_DATE','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_DISCHARGE_1_MISCARRIED_DATE2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_EPA_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER_TXT','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER1','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_0_SOURCE_OTHER3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_MIECHVP_COM','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_MIECHVP_FORM','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_MIECHVP_TRIBAL','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_OTHER1','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_OTHER2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_OTHER3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_END_PFS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_MIECHVP_COM','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_MIECHVP_FORM','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_MIECHVP_TRIBAL','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_OTHER1','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_OTHER2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_FUNDING_1_START_OTHER3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_HEALTH_GENERAL_0_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_HEALTH_PREGNANCY_0_EDD','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Client_Id','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_INCOME_INKIND_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_INCOME_OTHER_SOURCES','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_LS_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_MEDICAID_NUMBER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NCCO_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NI_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NT_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_NVC_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PC_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_DOB_INTAKE','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_FIRST','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PERSONAL_0_NAME_LAST','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PO_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_PRA_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_RD_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_RP_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SCA_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SE_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_SECOND_0_CHILD_DOB','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TALKED_0_WITH_ALT','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TALKED_1_WITH_OTHER_ALT','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TELEHEALTH_REASON_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TELEHEALTH_TYPE_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_1_DOB','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_10_DOB','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_2_DOB','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_3_DOB','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_4_DOB','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_5_DOB','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_6_DOB','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_7_DOB','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_8_DOB','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_TRIBAL_CHILD_9_DOB','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VE_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VEC_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLIENT_VQ_COMMENTS','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ClientID','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ClientName','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Comments','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CRM_Client_ID','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Date_Created','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('DateOfReport','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('DOB','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('DW_AuditDate','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Email','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('EndDate','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ETO_CaseNo','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('First_Name','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Home_Phone','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_0_ID_NSO3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_0_DOB','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_0_DOB2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_0_DOB3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_BIRTH_1_NICU_NURSERY_PURPOSE_OTHER3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INGEST_DATE1','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INGEST_DATE2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INGEST_DATE3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INJ_DATE1','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INJ_DATE2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_INJ_DATE3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON1','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHER_REASON3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHERDT1','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHERDT2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_ER_1_OTHERDT3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INGEST_DATE1','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INGEST_DATE2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INGEST_DATE3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INJ_DATE1','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INJ_DATE2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_HEALTH_HOSP_1_INJ_DATE3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_FIRST NAME3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_LAST NAME','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_NAME_FIRST','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_NAME_LAST','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_PERSONAL_0_SSN','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON1_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON2_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REASON3_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REFDATE1','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REFDATE2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_NHV_REFDATE3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON1_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON2_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REASON3_OTHER','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REFDATE1','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REFDATE2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('INFANT_SOCIAL_SERVICES_1_REFDATE3','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Last_Name','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('LastModified','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Middle_Name','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('MN_INFANT_0_ID_2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Pager','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Passcode','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ProgramStartDate','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Question13','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Question14','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_0_NOTES','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_0_NAME_LAST','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_CELL','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_DOB','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_EDD','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_EMAIL','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_NAME_FIRST','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_PHONE_HOME','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_STREET','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_STREET2','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_WORK','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_PROSPECT_DEMO_1_ZIP','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_PRIMARY_0_NAME','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_PRIMARY_1_LOCATION','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_SECONDARY_0_NAME','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('REFERRAL_SOURCE_SECONDARY_1_LOCATION','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER1_DESC','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER2_DESC','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SERIVCE_REFER_0_OTHER3_DESC','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SSN','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('State','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('StatusDate','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SurveyDate','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('SurveyDueDate','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('Work_Phone','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('ZipCode','SA')
insert into @hash_policy_map (pseudonym, policy_codifier) values ('CLID','SA')



if(@p_requested_hashing_policy is null) -- no requested hashing policy so just return as requested
begin

print 'in no policy'

	select 
		fr.survey_response_id,
		sq.pseudonym,
 		coalesce(fr.text_response,
									cast(fr.numeric_response as varchar),
									cast(fr.date_response as varchar), 
									cast(fr.boolean_response as varchar))
		 as secured_response

	   from fact_survey_response			fr  
		inner join dim_survey_question      sq		on fr.survey_question_key			= sq.survey_question_key
  
	  where 
		sq.survey_name = @p_survey_name
 
	  group by 
  
		fr.survey_response_id,
		sq.pseudonym,
		coalesce(fr.text_response,cast(fr.numeric_response as varchar),cast(fr.date_response as varchar), cast(fr.boolean_response as varchar));

end
else
begin -- in hashing policy so hash if the pseudo matches the policy

print 'in policy'

	select 
		fr.survey_response_id,
		sq.pseudonym,
		case
			when (@p_requested_hashing_policy=hpm.policy_codifier) 
			
			then survey_views.f_hash_field( 
								coalesce(fr.text_response,
									cast(fr.numeric_response as varchar),
									cast(fr.date_response as varchar), 
									cast(fr.boolean_response as varchar)))
			
			else 				coalesce(fr.text_response,
									cast(fr.numeric_response as varchar),
									cast(fr.date_response as varchar), 
									cast(fr.boolean_response as varchar))
		 end
		 as secured_response--, 
		 --hpm.policy_codifier


	   from fact_survey_response					fr  
			inner	join dim_survey_question		sq			on fr.survey_question_key			= sq.survey_question_key
			
			left	join (select distinct z.policy_codifier, z.pseudonym
							 from @hash_policy_map z where z.policy_codifier=@p_requested_hashing_policy)			
													hpm			on (hpm.pseudonym = sq.pseudonym )

  
	  where 
		sq.survey_name			= @p_survey_name

	  group by 
  
		fr.survey_response_id,
		sq.pseudonym,
		coalesce(fr.text_response,cast(fr.numeric_response as varchar),cast(fr.date_response as varchar), cast(fr.boolean_response as varchar)),
		hpm.policy_codifier
		--hpm.pseudonym;

end;


--select * from @hash_policy_map hpm where hpm.policy_codifier='MCVDUA'
















end;
